-- 1. Create the `products` table
create table public.products (
  id bigint generated by default as identity primary key,
  product_code text unique not null,
  shop_code text,
  product_name text not null,
  regional_name text,
  cost_price float default 0,
  sales_price float default 0,
  tax_percentage float default 0,
  category text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable Row Level Security (RLS)
alter table public.products enable row level security;

-- 3. Create Policy: Allow Public Read Access (For POS/Waiter)
create policy "Enable read access for all users"
on public.products for select
using (true);

-- 4. Create Policy: Allow Insert/Update/Delete for All (For Admin - Simplified)
-- In a real app, you would restrict this to authenticated users.
create policy "Enable write access for all users"
on public.products for insert
with check (true);

create policy "Enable update access for all users"
on public.products for update
using (true);

create policy "Enable delete access for all users"
on public.products for delete
using (true);

-- 5. Insert Sample Data
insert into public.products 
(product_code, product_name, regional_name, cost_price, sales_price, tax_percentage, category)
values
('BV001', 'Masala Chai', 'மசாலா டீ', 5.00, 15.00, 5, 'Beverages'),
('BV002', 'Filter Coffee', 'பில்டர் காபி', 7.00, 20.00, 5, 'Beverages'),
('ST001', 'Gobi 65', 'கோபி 65', 40.00, 120.00, 12, 'Starters'),
('MC001', 'Veg Biryani', 'வெஜ் பிரியாணி', 60.00, 180.00, 12, 'Main Course'),
('DS001', 'Gulab Jamun', 'குலாப் ஜாமுன்', 15.00, 45.00, 5, 'Desserts');
